name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    name: Type · Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Debug versions
        run: |
          node --version
          npm --version
          npm config get registry

      - name: Install dependencies
        run: npm ci --verbose

      - name: Type check
        run: npm run typecheck

      - name: Lint
        run: npm run lint
